apiVersion: v1
kind: ConfigMap
metadata:
  name: cayley-config-yaml-{{ .Release.Name }}
data:
  cayley.yml: |-
    store:
      # backend to use
      backend: memstore
      # address or path for the database
      address: "{{ .Values.config.dataPath }}"
      # open database in read-only mode
      read_only: true
      # backend-specific options
      options:
        nosync: true
    query:
      timeout: 150s