apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "cs-cayley.fullname" . }}
  labels:
    {{- include "cs-cayley.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "cs-cayley.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "cs-cayley.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "cs-cayley.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
              protocol: TCP
          livenessProbe:
            periodSeconds: 30
            failureThreshold: 5
            httpGet:
              path: /
              port: http
          readinessProbe:
            periodSeconds: 30
            failureThreshold: 5
            httpGet:
              path: /
              port: http
          volumeMounts:
            - mountPath: "/data"
              name: {{ .Values.environment.volumeName }}
            - mountPath: /data/cayley.yml
              name: cayley-config
              subPath: cayley.yml
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
        - name: {{ .Values.environment.volumeName }}
          persistentVolumeClaim:
            claimName: {{ .Values.environment.volumePvcName }}
        - name: cayley-config
          configMap:
            name: cayley-config-yaml-{{ .Release.Name }}
