{{- if .Values.service.enableNodePort  }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cs-cayley.fullname" . }}
  labels:
    {{- include "cs-cayley.labels" . | nindent 4 }}
spec:
  type: NodePort
  ports:
    - port: {{ .Values.service.port }}
      protocol: TCP
      name: main
  selector:
    app: {{ .Release.Name }}
{{ else }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "cs-cayley.fullname" . }}
  labels:
    {{- include "cs-cayley.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "cs-cayley.selectorLabels" . | nindent 4 }}
{{ end }}