{{ if .Files.Glob  "**.csdlic" }}
apiVersion: v1
kind: Secret
metadata:
  name: cs-license-secret
data:
  {{ range $path, $_ :=  .Files.Glob  "**.csdlic" }}
  cs-license.csdlic: |-
    {{ $.Files.Get $path | b64enc }}
  {{ end }}
{{ end }}