# Default values for cswebapi.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
fullnameOverride: cs-storage
imagePullSecrets: []
  # Optionally specify an array of imagePullSecrets.
  # Secrets must be manually created in the namespace.
  # ref: https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
  #
  # This uses credentials from secret "myRegistryKeySecretName".
  # - name: myRegistryKeySecretName
secrets: {}
  # Optionally specify a set of secret objects whose values
  # will be injected as environment variables by default.
  # You should add this section to a file like secrets.yaml
  # that is explicitly NOT committed to source code control
  # and then include it as part of your helm install step.
  # ref: https://kubernetes.io/docs/concepts/configuration/secret/
  #
  # This creates a secret "mysecret" and injects "mypassword"
  # as the environment variable mysecret_mypassword=password.
  # mysecret:
  #   mypassword: password
resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi
nodeSelector: {}

tolerations: []

affinity: {}

persistentVolumes:
  - name: cs-storage-pvc # PVC name - this is what each values.yaml of microservices will refers to.
    accessMode: ReadWriteOnce
    storage: 5Gi
    local: # This is a local PV setup for definining a hostPath on single node clusters ie. local kube
      - create: false # Determines if to use pv locally
        name: cs-dev-pv # Name of pv
        storageClassName: manual
        storage: 10Gi
        accessMode: ReadWriteMany
        path: "/run/desktop/mnt/host/c/data" # Path to the local folder specific to local kubernetes running on docker.
    efs: # This is for efs storage needs to be set to true when deploying on aws
      - create: true # This determines if to setup an efs pv on AWS
        name: cs-efs-pv # Name of pv
        storageClassName: cs-efs-sc
        reclaimPolicy: Retain
        storage: 10Gi
        accessMode: ReadWriteMany
        provisioner: efs.csi.aws.com # This is provisioner specific to aws
        fileSystemId: fs-0e47271f058efcbcd # This is a unique id of efs instance on aws, this will be customer specific