replicaCount: 1
image:
  repository: 167611410634.dkr.ecr.us-east-2.amazonaws.com/cs/cs-core
  pullPolicy: Always
  tag: 5.1.39-GA
imagePullSecrets: []
nameOverride: ''
fullnameOverride: cs-core
serviceAccount:
  annotations: {}
  create: false
  name: ''
podSecurityContext:
  fsGroup: 2000
  runAsGroup: 3000
  runAsUser: 1000
securityContext: {}
service:
  port: 9003
  type: LoadBalancer
deployment:
  containerPort: 9003
ingress:
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: instance
  enabled: false 
  hosts:
  - host: cs-core
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls:
  - secretName: none
    hosts:
    - none
resources:
  limits:
    cpu: 500m
  requests:
    cpu: 500m
    memory: 512M
autoscaling:
  enabled: true
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  scaleDownStabilizationPeriod: 600
  scaleUpStabilizationPeriod: 120
podAnnotations:
  prometheus.io/path: /metrics
  prometheus.io/port: '9003'
  prometheus.io/scrape: 'true'
  sidecar.jaegertracing.io/inject: 'true'
nodeSelector: {}
tolerations: []
affinity: {}
config:
  server:
    maxRequestQueueSize: 100
  Security:
    Enable: false
    Domain: null
    ApiIdentifier: null
    RequiresHttpsMetadata: false
    ScopeClaimKey: scope
  EventHandler:
    IsEnabled: false
    File:
      Name: Default
      FilePath: /data/TestNotifyFile.txt
    Http:
      Name: Default
      Uri: http://localhost:9003/api/test/echo
  Formatting:
    DefaultResponseFormat: application/xml
  Caching:
    PersistedCache:
      Location: /data/
    ResponseCacheEnable: true
    InternalCacheEnable: true
    DistributedCache:
      Enable: false
      SlidingExpirationInHours: 1
      Host: cs-redis-master.default.svc.cluster.local:6379,cs-redis-replicas.default.svc.cluster.local:6379
      Ssl: false
      SslHost: null
      SslProtocols: none
      ConnectTimeout: 5000
  RequestDefaults:
    EntitiesWith:
      EntitySummaryOnly: false
      TopEntityOnly: false
    Entities:
      EntitySummaryOnly: false
      TopEntityOnly: false
    EntitiesFactElementFilter:
      EntitySummaryOnly: false
      TopEntityOnly: false
    EntitiesClassifications:
      EntitySummaryOnly: false
      TopEntityOnly: false
    EntitiesWithClassificationsAndCharacteristics:
      EntitySummaryOnly: false
      TopEntityOnly: false
    EntitiesParents:
      EntitySummaryOnly: false
      TopEntityOnly: false
    CategoriesEntities:
      EntitySummaryOnly: false
      TopEntityOnly: false
    TypesEntities:
      EntitySummaryOnly: false
      TopEntityOnly: false
    RelatedEntities:
      EntitySummaryOnly: false
      TopEntityOnly: false
    CommercialEntities:
      EntitySummaryOnly: false
      TopEntityOnly: false
    FindWithParameters:
      EntitySummaryOnly: false
      TopEntityOnly: false
secrets:
  csLicenseSecret: cs-license-secret
environment:
  dataManagementConfig:
    host: cs-data-management
    port: '9004'
  Jaeger:
    AgentPort: 6831
  data:
    host: cs-cayley-a
    port: '64210'
    path: /data/EmptyData/data.nq
  logLevel: Information
  logToFile: false
  logFileLocation: /data/Logs/cs-core
  urls: http://*:9003
  volumePvcName: cs-storage-pvc
  volumeName: pvol
