replicaCount: 1
image:
  repository: 167611410634.dkr.ecr.us-east-2.amazonaws.com/cs/cs-builder
  pullPolicy: IfNotPresent
  tag: 5.1.27-GA
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
securityContext: {}
service:
  type: ClusterIP
  port: 9002
  enableNodePort: false
ingress:
  enabled: false
  className: alb
  annotations:
      alb.ingress.kubernetes.io/scheme: internet-facing
      alb.ingress.kubernetes.io/target-type: instance
  paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources:
  limits:
    cpu: 2000m
  requests:
    cpu: 500m
    memory: 512M
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9002'
  prometheus.io/path: /metrics
  sidecar.jaegertracing.io/inject: 'true'
nodeSelector: {}
tolerations: []
affinity: {}
environment:
  data:
    host: cs-cayley-a
    port: '64210'
    path: /data/EmptyData/data.nq
  Jaeger:
    AgentPort: 6831
  cacheLocation: /data/
  logLevel: Information
  logToFile: false
  logFileLocation: /data/Logs/cs-builder
  urls: http://*:9002
  volumePvcName: cs-storage-pvc
  volumeName: pvol
