replicaCount: 1
image:
  repository: 167611410634.dkr.ecr.us-east-2.amazonaws.com/cs/cs-data-management
  pullPolicy: IfNotPresent
  tag: 5.1.24-GA
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: dms-sa
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
securityContext: {}
service:
  type: ClusterIP
  port: 9004
deployment:
  containerPort: 9004
ingress:
  enabled: true
  className: ''
  annotations: {}
  hosts:
  - host: cs-data-management-csd-dev-cluster.internal.delivery.hansencx.com
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: 
    - secretName: nginx-ingress-secret
      hosts:
        - cs-data-management-csd-dev-cluster.internal.delivery.hansencx.com
resources:
  requests:
    cpu: 100m
    memory: 128M
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
podAnnotations:
  prometheus.io/scrape: 'true'
  prometheus.io/port: '9004'
  prometheus.io/path: /metrics
  sidecar.jaegertracing.io/inject: 'true'
nodeSelector: {}
tolerations: []
affinity: {}
kafka:
  enable: false
  topicSuffix: ''
  producerConfig:
    clientId: CatalogServices
    bootstrapServers: 'z-2.cnmskcsddev2.npjjqs.c3.kafka.us-east-2.amazonaws.com:2181,z-1.cnmskcsddev2.npjjqs.c3.kafka.us-east-2.amazonaws.com:2181,z-3.cnmskcsddev2.npjjqs.c3.kafka.us-east-2.amazonaws.com:2181'
    securityProtocol: Plaintext
    enableSslCertificateVerification: false
    sslEndpointIdentificationAlgorithm: None
    acks: All
    saslMechanism: null
    saslUsername: null
    saslPassword: null
environment:
  namespace: cs
  cayleyDeployment:
    path: /data/EmptyData/data.nq
    maxReplication: 1
    alpha:
      releaseName: cs-cayley-a
      host: cs-cayley-a
      port: '64210'
    beta:
      releaseName: cs-cayley-b
      host: cs-cayley-b
      port: '64210'
  builderDeployment:
    releaseName: cs-builder
    host: cs-builder
    port: '9002'
  coreDeployment:
    releaseName: cs-core
  Jaeger:
    AgentPort: 6831
  logLevel: Information
  logToFile: false
  logFileLocation: /data/Logs/cs-data-management
  urls: http://*:9004
  volumePvcName: cs-storage-pvc
  volumeName: pvol
