replicaCount: 1
image:
  repository: 167611410634.dkr.ecr.us-east-2.amazonaws.com/cs/cs-cayley
  tag: 5.1.22-GA
  pullPolicy: IfNotPresent
imagePullSecrets: []
nameOverride: ''
fullnameOverride: ''
serviceAccount:
  create: false
  annotations: {}
  name: ''
podAnnotations: {}
podSecurityContext:
  runAsUser: 1000
  runAsGroup: 3000
  fsGroup: 2000
securityContext: {}
service:
  type: ClusterIP
  port: 64210
  enableNodePort: false
deployment:
  containerPort: 64210
ingress:
  enabled: true
  className: alb
  annotations:
        alb.ingress.kubernetes.io/scheme: internet-facing
        alb.ingress.kubernetes.io/target-type: instance
  hosts:
  - host: cs-cayley
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
resources:
  requests:
    cpu: 100m
    memory: 128M
nodeSelector: {}
tolerations: []
affinity: {}
environment:
  volumePvcName: cs-storage-pvc
  volumeName: pvol
config:
  dataPath: /cayley/data.nq
