{
 "title": "Catalog Services Dashboard",
 "tags": [
  "prometheus-net",
  "net",
  "prometheus",
  ".net",
  ".net core"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "app",
    "label": "app",
    "query": {
     "query": "label_values(http_requests_received_total, app)"
    }
   },
   {
    "name": "pods",
    "label": "pods",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\"}, kubernetes_pod_name)"
    }
   },
   {
    "name": "controllers",
    "label": "controllers",
    "query": {
     "query": "label_values(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name=~ \"$pods\"}, controller)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Uptime",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "time() - process_start_time_seconds{app=~\"$app\", kubernetes_pod_name =~ \"$pods\"}"
    }
   ]
  },
  {
   "title": "Start time",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}"
    }
   ]
  },
  {
   "title": "Health",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 5, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalog_services_health_check {app =~ \"$app\", kubernetes_pod_name =~ \"$pods\" }",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Throughput",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(http_request_duration_seconds_sum{ app =~ \"$app\", kubernetes_pod_name =~ \"$pods\" }[5m])) * 60",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  {
   "title": "License Expires in",
   "type": "gauge",
   "description": "The Hansen Catalog Services License status.",
   "gridPos": { "h": 7, "w": 4, "x": 17, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "d" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "catalog_services_license_status",
     "legendFormat": "{{licensedTo}}"
    }
   ]
  },
  {
   "title": "Licensed To",
   "type": "stat",
   "gridPos": { "h": 7, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "catalog_services_license_status"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m]) * 60",
     "legendFormat": "{{method}} /{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Response Time / Endpoint",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m])",
     "legendFormat": "{{method}} /{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Percentiles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m])) by (le))",
     "legendFormat": "99 %"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m])) by (le))",
     "legendFormat": "95 %"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m])) by (le))",
     "legendFormat": "90 %"
    }
   ]
  },
  {
   "title": "Request Outcome",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(http_request_duration_seconds_count{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\"}) by (code)",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "legendFormat": "{{code}}",
     "measurement": "application.httprequests__transactions",
     "select": [
      [
       { "params": [ "rate1m" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "app", "operator": "=~", "value": "/^$application$/" },
      { "condition": "AND", "key": "env", "operator": "=~", "value": "/^$environment$/" }
     ]
    }
   ]
  },
  { "title": "Endpoints", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Response Time / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_sum{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[5m])",
     "legendFormat": "{{method}} /{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Throughput / Endpoint",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "rate(http_request_duration_seconds_count{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[5m]) * 60",
     "legendFormat": "{{method}} /{{controller}}/{{action}}"
    }
   ]
  },
  {
   "title": "Request rate",
   "type": "timeseries",
   "description": "Counts all requests, both successful and failed",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[5m])) by (controller)",
     "legendFormat": "{{method}} {{controller}} {{action}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"\"}[5m]))",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "timeseries",
   "description": "4xx and 5xx status codes",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(rate(http_requests_received_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\", code =~ \"5\\\\d\\\\d|4\\\\d\\\\d\"}[5m])) by (controller)",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  {
   "title": "Request duration",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\" }[5m])) by (controller)",
     "legendFormat": "{{controller}}"
    },
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{ app=~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller = \"\" }[5m])) by (controller)",
     "legendFormat": "(None)"
    }
   ]
  },
  {
   "title": "Request duration (controller-handled requests only)",
   "type": "heatmap",
   "description": "Does NOT include requests that were not mapped to an ASP.NET Core controller!",
   "gridPos": { "h": 18, "w": 12, "x": 12, "y": 42 },
   "targets": [
    {
     "expr": "sum(increase(http_request_duration_seconds_bucket{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\", controller =~ \"$controllers\"}[5m])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Requests currently in progress",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 51 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "http_requests_in_progress{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  },
  { "title": "Storage and Compute", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 60 } },
  {
   "title": "Cpu usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum (rate (container_cpu_usage_seconds_total{container =~ \"$app\", pod =~ \"$pods\"}[5m])) by (pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Memory usage",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{container =~ \"$app\", pod =~ \"$pods\"}) by (pod_name)",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Total number of threads",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_num_threads{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Total known allocated memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 70 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "dotnet_total_memory_bytes{ app=~\"$app\", kubernetes_pod_name=~\"$pods\"} /1024/1024",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "GC collection count",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "increase(dotnet_collection_count_total{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}[5m])",
     "legendFormat": "{{kubernetes_pod_name }}-Generation-{{generation}}"
    }
   ]
  },
  {
   "title": "Process working set",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 79 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_working_set_bytes{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"} /1024/1024",
     "legendFormat": "{{kubernetes_pod_name}}"
    }
   ]
  },
  {
   "title": "Number of open handles",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 88 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "process_open_handles{app =~ \"$app\", kubernetes_pod_name =~ \"$pods\"}",
     "legendFormat": "{{kubernetes_pod_name }}"
    }
   ]
  }
 ]
}